In [1]:
import torch
import torch.nn as nn

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024**3,1), 'GB')

Using device: cuda

NVIDIA GeForce GTX 1050 Ti
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB


In [3]:
torch.rand(10).to(device)

tensor([0.3052, 0.3646, 0.9616, 0.8369, 0.1835, 0.2586, 0.4948, 0.7437, 0.1510,
        0.6535], device='cuda:0')

In [4]:
torch.rand(10, device=device)

tensor([0.7494, 0.3391, 0.8133, 0.9431, 0.9373, 0.1029, 0.4724, 0.8632, 0.8041,
        0.1318], device='cuda:0')

In [5]:
t1 = torch.randn(1,2)
t2 = torch.randn(1,2).to(device)
print(t1)  # tensor([[-0.2678,  1.9252]])
print(t2)  # tensor([[ 0.5117, -3.6247]], device='cuda:0')
t1.to(device)
print(t1)  # tensor([[-0.2678,  1.9252]])
print(t1.is_cuda) # False
t1 = t1.to(device)
print(t1)  # tensor([[-0.2678,  1.9252]], device='cuda:0')
print(t1.is_cuda) # True

tensor([[ 1.9623, -0.1943]])
tensor([[ 0.8509, -2.1497]], device='cuda:0')
tensor([[ 1.9623, -0.1943]])
False
tensor([[ 1.9623, -0.1943]], device='cuda:0')
True


In [6]:
class M(nn.Module):
    def __init__(self):        
        super().__init__()        
        self.l1 = nn.Linear(1,2)

    def forward(self, x):                      
        x = self.l1(x)
        return x
model = M()   # not on cuda
model.to(device) # is on cuda (all parameters)
print(next(model.parameters()).is_cuda) # True

True
